### ISSUE TITLE
Where To Get The Demo Project

### ISSUE THREAD

**Issue by yhnu** [yasirkula/UnityDynamicPanels#5]
Hi, Thank you very much for your tools. Where To Get The Demo Project?
![image](https://user-images.githubusercontent.com/23090916/68522375-862bb880-02e5-11ea-88c1-9c3daa4ec672.png)

**Comment by yasirkula** [comment]
It is not available since it uses assets other than DynamicPanels. If you are interested, the [new demo project](http://yasirkula.net/DynamicPanelsDemo/) is available at: https://drive.google.com/open?id=1bAHEDF1AQ03rECr2kh9AxymClXrvrhLW

It requires the following assets in addition to DynamicPanels:

https://github.com/yasirkula/UnityRuntimeInspector/
https://github.com/yasirkula/UnityIngameDebugConsole/
https://github.com/yasirkula/UnityRuntimeSceneGizmo/
