### ISSUE TITLE
[Suggestion] Close Button

### ISSUE THREAD

**Issue by aytimothy** [yasirkula/UnityDynamicPanels#6]
Seems a bit silly, but in Unity, you can close panels by right clicking them and clicking "Close Tab" or the "X" button.

![image](https://user-images.githubusercontent.com/7418834/100538968-a9256380-327e-11eb-81d1-5214b2534438.png)

It's great that you can already do this using `PanelTab.Destroy()`, but a in-built "X" button would be nice.

Other than that, really well done in terms of ease of going from a random `RectTransform` to a panel managed by your system.

**Comment by yasirkula** [comment]
The issue here is that, it is ambiguous what will happen when the button is clicked. Some users would probably want to disable the panel (then there is the issue of how to reactivate it), some would want to destroy it and some would want to detach and disable the content, then destroy the panel.

I may add an event to DynamicPanelsCanvas and enable the destroy tab button only if a function is registered to this event.

**Comment by aytimothy** [comment]
Cool, thanks!

(And I see you already did that)
